//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRegApp
{
    public partial class ViewLeaveApplications
    {
        protected global::System.Web.UI.WebControls.GridView gvLeaveApplications;
    }
}